const data = {
  products: [
    {
      _id: 1,
      image: "/images/d1.jpg",
      name: "Slim-shirt",
      brand: "Nike",
      price: "NRS 1600",
      reviews: "4.5 Stars (10 Reviews)",
    },
    {
      _id: 2,
      image: "/images/d2.jpg",
      name: "Design-Shirt",
      brand: "Kens-star",
      price: "NRS 1350",
      reviews: "4.2 Stars (8 Reviews)",
    },
    {
      _id: 3,
      image: "/images/d3.jpg",
      name: "Tight-Shirt",
      brand: "Blaze",
      price: "NRS 1650",
      reviews: "4.5 Stars (15 Reviews)",
    },
    {
      _id: 4,
      image: "/images/d4.jpg",
      name: "Black-white-Shirt",
      brand: "ComFort",
      price: "NRS 1450",
      reviews: "4.0 Stars (6 Reviews)",
    },
    {
      _id: 5,
      image: "/images/d5.jpg",
      name: "Fit-Shirt",
      brand: "Zemtoo",
      price: "NRS 1800",
      reviews: "4.5 Stars (17 Reviews)",
    },
    {
      _id: 6,
      image: "/images/d6.jpg",
      name: "Bow-Shirt",
      brand: "Kens-star",
      price: "NRS 1400",
      reviews: "4.2 Stars (10 Reviews)",
    },
    {
      _id: 7,
      image: "/images/d7.jpg",
      name: "Best-Shirt",
      brand: "Laravi",
      price: "NRS 1800",
      reviews: "4.8 Stars (20 Reviews)",
    },
  ],
};
export default data;
