const data = {
  products: [
    {
      _id: "1",
      image: "/images/d1.jpg",
      name: "Slim-shirt",
      brand: "Nike",
      price: "NRS 1600",
      reviews: "4.5 Stars (10 Reviews)",
      countInStock: 4,
    },
    {
      _id: "2",
      image: "/images/d2.jpg",
      name: "Design-Shirt",
      brand: "Kens-star",
      price: "NRS 1350",
      reviews: "4.2 Stars (8 Reviews)",
      countInStock: 0,
    },
    {
      _id: "3",
      image: "/images/d3.jpg",
      name: "Tight-Shirt",
      brand: "Blaze",
      price: "NRS 1650",
      reviews: "4.5 Stars (15 Reviews)",
      countInStock: 7,
    },
    {
      _id: "4",
      image: "/images/d4.jpg",
      name: "Black-white-Shirt",
      brand: "ComFort",
      price: "NRS 1450",
      reviews: "4.0 Stars (6 Reviews)",
      countInStock: 6,
    },
    {
      _id: "5",
      image: "/images/d5.jpg",
      name: "Fit-Shirt",
      brand: "Zemtoo",
      price: "NRS 1800",
      reviews: "4.5 Stars (17 Reviews)",
      countInStock: 5,
    },
    {
      _id: "6",
      image: "/images/d6.jpg",
      name: "Bow-Shirt",
      brand: "Kens-star",
      price: "NRS 1400",
      reviews: "4.2 Stars (10 Reviews)",
      countInStock: 1,
    },
    {
      _id: "7",
      image: "/images/d7.jpg",
      name: "Best-Shirt",
      brand: "Laravi",
      price: "NRS 1800",
      reviews: "4.8 Stars (20 Reviews)",
      countInStock: 7,
    },
    {
      _id: "8",
      image: "/images/d9.jpg",
      name: "Blaze-Shirt",
      brand: "Laravi",
      price: "NRS 1650",
      reviews: "4.7 Stars(22 Reviews)",
      countInStock: 10,
    },
  ],
};
export default data;
